# Generated by Django 5.1.2 on 2025-11-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio_process", "0003_speakersegment_emotion_confidence_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="speakersegment",
            options={"ordering": ["recording", "turn_index"]},
        ),
        migrations.AddField(
            model_name="speakersegment",
            name="turn_index",
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
