# Generated by Django 5.1.2 on 2025-11-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audio_process", "0004_alter_speakersegment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="speakersegment",
            options={"ordering": ["session_id", "turn_index"]},
        ),
        migrations.RenameField(
            model_name="speakersegment",
            old_name="recording",
            new_name="session_id",
        ),
    ]
