# Generated by Django 5.1.2 on 2025-11-26 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio_process", "0005_alter_speakersegment_options_and_more"),
        ("logical_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeranalysisresult",
            name="classification_probabilities",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="customeranalysisresult",
            name="profanity_method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customeranalysisresult",
            name="score_hate_speech",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="customeranalysisresult",
            name="score_repetition",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="customeranalysisresult",
            name="score_sexual_harassment",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="customeranalysisresult",
            name="segment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="customer_analysis",
                serialize=False,
                to="audio_process.speakersegment",
            ),
        ),
        migrations.AlterModelTable(
            name="customeranalysisresult",
            table="customer_analysis_results",
        ),
    ]
