# Generated by Django 5.2.8 on 2025-11-24 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio_process", "0003_speakersegment_emotion_confidence_and_more"),
        ("logical_analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogicalResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speech_speed", models.FloatField(blank=True, null=True)),
                ("pause_duration", models.FloatField(blank=True, null=True)),
                ("is_overlap", models.BooleanField(default=False)),
                ("profanity_score", models.FloatField(blank=True, null=True)),
                ("threat_score", models.FloatField(blank=True, null=True)),
                ("insistence_score", models.FloatField(blank=True, null=True)),
                (
                    "intent_label",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("manual_compliance_score", models.FloatField(blank=True, null=True)),
                ("empathy_score", models.FloatField(blank=True, null=True)),
                ("context_appropriateness", models.FloatField(blank=True, null=True)),
                (
                    "segment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logical_analysis",
                        to="audio_process.speakersegment",
                    ),
                ),
            ],
            options={
                "db_table": "logical_results",
                "ordering": ["segment__start_time"],
            },
        ),
        migrations.DeleteModel(
            name="ClassificationResult",
        ),
    ]
