# Generated by Django 5.1.2 on 2025-11-26 03:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio_process", "0003_speakersegment_emotion_confidence_and_more"),
        ("logical_analysis", "0002_logicalresult_delete_classificationresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerAnalysisResult",
            fields=[
                (
                    "segment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="analysis_result",
                        serialize=False,
                        to="audio_process.speakersegment",
                    ),
                ),
                ("label", models.CharField(max_length=50)),
                ("label_type", models.CharField(max_length=20)),
                ("classification_confidence", models.FloatField(default=0.0)),
                ("is_profanity", models.BooleanField(default=False)),
                (
                    "profanity_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "score_risk",
                    models.FloatField(
                        default=0.0, help_text="Turn 단위 종합 리스크 점수"
                    ),
                ),
                ("score_profanity", models.FloatField(default=0.0)),
                ("score_threat", models.FloatField(default=0.0)),
                ("score_unreasonable_demand", models.FloatField(default=0.0)),
                ("extracted_features", models.JSONField(blank=True, default=dict)),
                ("feature_scores_extra", models.JSONField(blank=True, default=dict)),
                (
                    "analyzed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "고객 분석 결과",
            },
        ),
        migrations.DeleteModel(
            name="LogicalResult",
        ),
    ]
