# Generated by Django 5.1.2 on 2025-11-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "logical_analysis",
            "0002_customeranalysisresult_classification_probabilities_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customeranalysisresult",
            name="immorality_confidence",
            field=models.FloatField(
                blank=True, help_text="비도덕성 판단 신뢰도", null=True
            ),
        ),
        migrations.AddField(
            model_name="customeranalysisresult",
            name="intensity",
            field=models.FloatField(
                blank=True, help_text="감정/발화 강도 (0.0~3.0)", null=True
            ),
        ),
        migrations.AddField(
            model_name="customeranalysisresult",
            name="intensity_level",
            field=models.CharField(
                blank=True, help_text="LOW, MEDIUM, HIGH", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="customeranalysisresult",
            name="is_immoral",
            field=models.BooleanField(
                default=False, help_text="비도덕적/모욕적 발언 여부"
            ),
        ),
    ]
