# Generated by Django 5.2.8 on 2025-11-24 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audio_process", "0003_speakersegment_emotion_confidence_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponseManual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("situation_title", models.CharField(max_length=255)),
                ("target_emotion", models.CharField(max_length=100)),
                ("target_logic_flaw", models.CharField(max_length=100)),
                ("script", models.TextField()),
                ("action_guide", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SolutionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "matched_manual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solution_results",
                        to="solution_system.responsemanual",
                    ),
                ),
                (
                    "segment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solution_result",
                        to="audio_process.speakersegment",
                    ),
                ),
            ],
        ),
    ]
