# Generated by Django 4.2.26 on 2025-11-26 11:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audio_process", "0005_alter_speakersegment_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolutionResult",
            fields=[
                (
                    "segment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="solution_result",
                        serialize=False,
                        to="audio_process.speakersegment",
                    ),
                ),
                ("input_emotion_label", models.CharField(max_length=50)),
                ("input_logical_label", models.CharField(max_length=50)),
                ("input_logical_type", models.CharField(max_length=20)),
                ("input_risk_score", models.FloatField(default=0.0)),
                (
                    "input_profanity_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "strategy_title",
                    models.CharField(help_text="대응 전략 제목", max_length=200),
                ),
                ("strategy_description", models.TextField(help_text="전략 상세 설명")),
                (
                    "tone_and_manner",
                    models.CharField(help_text="권장 어조", max_length=200),
                ),
                (
                    "required_keywords",
                    models.JSONField(default=list, help_text="필수 키워드"),
                ),
                (
                    "prohibited_keywords",
                    models.JSONField(default=list, help_text="금지 키워드"),
                ),
                (
                    "solution_scripts",
                    models.JSONField(default=list, help_text="추천 스크립트 목록"),
                ),
                (
                    "checkpoints",
                    models.JSONField(default=list, help_text="상담원 체크포인트"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "상담 솔루션 결과",
                "db_table": "solution_result",
            },
        ),
    ]
