# Generated by Django 5.1.2 on 2025-11-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solution_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="solutionresult",
            options={"verbose_name": "상담 솔루션"},
        ),
        migrations.RemoveField(
            model_name="solutionresult",
            name="input_emotion_label",
        ),
        migrations.RemoveField(
            model_name="solutionresult",
            name="input_logical_label",
        ),
        migrations.RemoveField(
            model_name="solutionresult",
            name="input_logical_type",
        ),
        migrations.RemoveField(
            model_name="solutionresult",
            name="input_profanity_category",
        ),
        migrations.RemoveField(
            model_name="solutionresult",
            name="input_risk_score",
        ),
        migrations.RemoveField(
            model_name="solutionresult",
            name="prohibited_keywords",
        ),
        migrations.RemoveField(
            model_name="solutionresult",
            name="required_keywords",
        ),
        migrations.AddField(
            model_name="solutionresult",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="solutionresult",
            name="checkpoints",
            field=models.JSONField(default=list, help_text="상담 시 유의사항 리스트"),
        ),
        migrations.AlterField(
            model_name="solutionresult",
            name="solution_scripts",
            field=models.JSONField(default=list, help_text="실제 응대 스크립트 리스트"),
        ),
        migrations.AlterField(
            model_name="solutionresult",
            name="strategy_description",
            field=models.TextField(help_text="상세 대응 가이드"),
        ),
        migrations.AlterField(
            model_name="solutionresult",
            name="strategy_title",
            field=models.CharField(
                help_text="대응 전략 제목 (예: 격앙된 고객 진정 유도)", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="solutionresult",
            name="tone_and_manner",
            field=models.CharField(
                help_text="권장 목소리 톤 (예: 차분하고 낮은 톤)", max_length=100
            ),
        ),
        migrations.AlterModelTable(
            name="solutionresult",
            table="solution_results",
        ),
    ]
